language: clojure

jdk:
  - oraclejdk8

install:
  - mkdir deps
  - (cd deps && curl -L https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh > boot && chmod 755 boot)
  - (cd deps && curl -L https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar xjf -)
  - export PATH=$PATH:`pwd`/deps:`pwd`/deps/phantomjs-2.1.1-linux-x86_64/bin
  - boot -u

script:
  - boot test-all
